### ISSUE TITLE
Add link to CRAN page on ropensci.org/packages

### ISSUE THREAD

**Issue by mwpennell** [ropensci/chromer#18]
Chromer is finally on CRAN. If you could link to it at some point, that would be great.

http://cran.r-project.org/web/packages/chromer/index.html

**Comment by sckott** [comment]
yeppers! on it https://github.com/ropensci/roweb/issues/153

**Comment by sckott** [comment]
done done and done http://ropensci.org/packages/ :dragon: :cow: :bird:

**Comment by mwpennell** [comment]
great. thanks @sckott
