### ISSUE TITLE
Tag the release

### ISSUE THREAD

**Issue by karthik** [ropensci/chromer#19]
Nice work Matt! Glad you got it in CRAN. Now you should click on releases, add a version number and copy over the contents of the NEWS file into the description. This is a good practice to do after each CRAN release. 

Then change the version number on the GitHub version from `0.1` to `0.1.0.9999` to indicate that this is now the dev/github version. As you add or fix features, bump up the third digit (currently `0`). For the next CRAN release round that `0.1` to `0.2`

**Comment by mwpennell** [comment]
Ok -- this is now done
