### ISSUE TITLE
Change README to include instructions for downloading via drat

### ISSUE THREAD

**Issue by mwpennell** [ropensci/chromer#20]
I would like to point users to the ROpenSci repo as a download option, but seem to be missing something here. If I type 

```
install.packages("chromer", repos = "http://packages.ropensci.org
```

it can't find it

```
Warning: unable to access index for repository http://packages.ropensci.org/bin/macosx/mavericks/contrib/3.2
```

and if I use something like

```
install.packages("chromer", repos = c("http://packages.ropensci.org", "http://cran.rstudio.com"))
```

I get

```
Warning: unable to access index for repository http://packages.ropensci.org/bin/macosx/mavericks/contrib/3.2
trying URL 'http://cran.rstudio.com/bin/macosx/mavericks/contrib/3.2/chromer_0.1.tgz'
Content type 'application/x-gzip' length 17949 bytes (17 KB)
```

I do not have the same issue when I install taxize via this method. Am I missing something? Do I need to do something to set chromer up in the ROpenSci repo? cc: @sckott @cboettig

**Comment by karthik** [comment]
@mwpennell We probably missed it in the list and that can be remedied shortly.

**Comment by mwpennell** [comment]
Ok, thanks!
