### ISSUE TITLE
chromer is not working for me

### ISSUE THREAD

**Issue by fbalao** [ropensci/chromer#21]
The package is not working for me. Any suggestion?
> library(chromer)
> chrom_counts("Castilleja", "genus")
Error in attr(res, "class") <- c(attr(res, "class"), "chrom.counts") : 
  se intenta especificar un atributo en un NULL

**Comment by sckott** [comment]
@fbalao  i made a fix, though not merged into master yet, try installing like ` devtools::install_github("ropensci/chromer@sckott-fixes")`, then retrying your eg

**Comment by fbalao** [comment]
@sckott now it works like a charm. Thanks

**Comment by rossmounce** [comment]
Just to say the main repo (https://github.com/ropensci/chromer) code still hasn't been updated, I'm getting the same problem as @fbalao describes.

It's not obvious from the front page of the repo that there's a solution. I'm not sure that all potential users will be savvy enough to check the issues for a fix... Are there plans to merge to master?  @sckott

**Comment by sckott** [comment]
Thanks for the ping @rossmounce 

I'll merge today

**Comment by sckott** [comment]
okay, merged to master @fbalao @rossmounce
