### ISSUE TITLE
ORCID identifier and search keywords for JSON-LD metadata

### ISSUE THREAD

**Issue by chrisfan24** [ropensci/chromer#25]
👋  @mwpennell 

I'm using codemetar to create JSON-LD metadata for rOpenSci packages. When you have the time, could you help me out with some info? In particular, I need your ORCID identifier as well as some keywords for the package that would help for search.

Thanks and let me know if you need me to elaborate on what I'm doing!

**Comment by orchid00** [comment]
hi @chrisfan24 
I'm the new maintainer for this project, you can have a look here for most the the required metadata. https://github.com/ropensci/chromer/blob/master/codemeta.json I also wanted to add Matthew Pennell's orcid but couldn't find it online. 

Do you need any other info?

**Comment by kbroman** [comment]
It looks like his ORCID is [0000-0002-2886-3970](https://orcid.org/0000-0002-2886-3970); for example see [Falster et al 2019](https://doi.org/10.1093/gigascience/giz035).
