### ISSUE TITLE
 Error in chrom_counts_single

### ISSUE THREAD

**Issue by lucaslima1618** [ropensci/chromer#27]
Hi,

Chromer is not working for while, it keeps given this error mensage:

 Error in chrom_counts_single(x, rank, out, foptions = foptions) : 
  Internal Server Error (HTTP 500). 

What should I do to fix this issue?

thanks

**Comment by orchid00** [comment]
Hi Lucas, I've recently became maintainer old chrome. I'll see what I can do to fix the problem. I'm just seeing this issue and my guess is a conflict with the R version. Would please let me know which version you are using? You can type `version` in the console and you will know. Thanks!

**Comment by lucaslima1618** [comment]
Hi Paula,

Thanks for help me. My R version is  3.5.3 (2019-03-11).

Kind regards,

**Comment by orchid00** [comment]
Thanks @lucaslima1618 R version 3.5.3 is a major release is likely to have changed many things. Are you able to provide me with a reproducible example so I can check it for you?

**Comment by orchid00** [comment]
I think I found the problem
> NotImplementedError at /services/countsFull/
`request.QUERY_PARAMS` has been deprecated in favor of `request.query_params` since version 3.0, and has been fully removed as of version 3.2.

**Comment by orchid00** [comment]
i've contacted Itay from CCDB

**Comment by orchid00** [comment]
@lucaslima1618 the problem has been solved.
