### ISSUE TITLE
NULL cannot have an attribute

### ISSUE THREAD

**Issue by chenqh0618** [ropensci/chromer#29]
> chrom_counts("Castilleja_miniata", "species")

Error in attr(res, "class") <- c(attr(res, "class"), "chrom.counts") : 
  NULL cannot have an attribute

**Comment by orchid00** [comment]
hi @chenqh0618, thanks for reporting this. 
I will look into it in the coming days.

**Comment by orchid00** [comment]
@chenqh0618 I wasn't able to reproduce the error. 
Would you be able to install the package again, and then run your code once more?
or try this: `a <- chrom_counts(taxa = "Castilleja_miniata", rank = "species")`

the result is a tibble of 11 X 4

**Comment by chenqh0618** [comment]
sorry,

I tried installed the package again and code you suggested, but returned the same answer

"NULL cannot have an attribute"

Thanks anyway~

**Comment by orchid00** [comment]
Hi @chenqh0618 
what is your R version? I tested with R version 3.6.2, 3.6.1, 3.5.3, 3.5.2. You can check by typing version in the console. If your version is older than R version 3.5.3 (Great Truth) it is suggest that you update it, keeping in mind you might need to update multiple packages too.
You also need a stable internet connection. 
Those are the issues I can think of.

If you are using R studio, you could restart R (ctrl+Shift+F10)
then run
```
devtools::install_github("ropensci/chromer")

library(chromer)
chrom_counts("Castilleja_miniata", "species")
```

Today, I've asked other people to run these three lines and I will

**Comment by chenqh0618** [comment]
Thanks a lot, 
the problem has been sovled when I installed the package from github as you suggested!

I am using R studio with R in version 3.6.2, the error might be caused my unsuitable installing from CRAN~

**Comment by orchid00** [comment]
Cool, so we solved one problem. 🎉 

I'll be looking at updating the CRAN version in the coming days.
