### ISSUE TITLE
New Maintainer Wanted :-)

### ISSUE THREAD

**Issue by maelle** [ropensci/chromer#33]
Or new maintainer team. :smile_cat: 

If you're interested, please comment in the issue.
For more info, see
- [our guidance on Changing package maintainers](https://devguide.ropensci.org/changing-maintainers.html);
- [our Package Curation Policy](https://devguide.ropensci.org/curationpolicy.html).

**Comment by kbroman** [comment]
I’d be willing to take over maintenance of this package and get it back on CRAN.

Could we change the license from CC0 to MIT? I’d like to have the “no warranty” clause.

**Comment by maelle** [comment]
@kbroman Thanks so much! I've now added you to a team with admin access to this repository.

Yes you can change the licence (noting IANAL :grin:). ICYMI and in case it is relevant: https://www.tidyverse.org/blog/2021/12/relicensing-packages/

Do you need a (new) invitation to our Slack workspace, where there's a friendly #package-maintenance channel? If so, to which email address?

**Comment by kbroman** [comment]
Super, thanks! I've started [an issue to re-license the package](https://github.com/ropensci/chromer/issues/35).

I do still have access to the Slack workspace.

**Comment by maelle** [comment]
Thank _you_!!
