### ISSUE TITLE
Re-license chromer

### ISSUE THREAD

**Issue by kbroman** [ropensci/chromer#35]
I'm taking over maintenance of the chromer package and would like to re-license it to use the MIT license, particularly for the "no warranty" clause. Following [the procedure used by RStudio](https://www.tidyverse.org/blog/2021/12/relicensing-packages/) (see the [re-licensing issue for purr](https://github.com/tidyverse/purrr/issues/805)), I need the approval of all copyright holders, which appear to be @mwpennell, @orchid00, and @sckott. Would you permit me to re-license chromer with the MIT license?  If so, please comment "I agree" below.

* [x] @mwpennell 
* [x] @orchid00
* [x] @sckott

**Comment by sckott** [comment]
I agree

**Comment by mwpennell** [comment]
I agree

**Comment by orchid00** [comment]
I agree

Thanks for taking over the maintenance @kbroman

**Comment by kbroman** [comment]
super, thanks!
