### ISSUE TITLE
Error in `dplyr::bind_rows()`

### ISSUE THREAD

**Issue by zhangrengang** [ropensci/chromer#39]
Hi, I got an error about `dplyr` as following:
```
> library(chromer)
Warning message:
replacing previous import ‘vctrs::data_frame’ by ‘tibble::data_frame’ when loading ‘dplyr’
> sol_gen <- chrom_counts(taxa = "Solanum", rank = "genus")
Error in `dplyr::bind_rows()`:
! Argument 1 must have names.
> sol_gen
Error: object 'sol_gen' not found
```
Is it an issue of `dplyr` version? How can I do with it?

**Comment by Treebeard27** [comment]
I am also having an issue that sounds similar, but I have a different warning from R (version 4.3.1).
```
> sol_fam <- chrom_counts(taxa = "Solanaceae", rank = "family")
Error in `dplyr::bind_rows()`:
! Argument 1 must be a data frame or a named atomic vector.
Run `rlang::last_trace()` to see where the error occurred.
> rlang::last_trace()
<error/rlang_error>
Error in `dplyr::bind_rows()`:
! Argument 1 must be a data frame or a named atomic vector.
---
Backtrace:
    ▆
 1. └─chromer::chrom_counts(taxa = "Solanaceae", rank = "family")
 2.   └─base::lapply(...)
 3.     └─chromer (local) FUN(X[[i]], ...)
 4.       └─chromer:::chrom_counts_single(x, rank, out, foptions = foptions)
 5.         ├─base::data.frame(dplyr::bind_rows(counts_data_json))
 6.         └─dplyr::bind_rows(counts_data_json)
 7.           └─rlang::abort(glue("Argument {i} must be a data frame or a named atomic vector."))
```

**Comment by kbroman** [comment]
Sorry to come to this 2 months late, but I totally missed this.

Currently, the chromer API seems to be down. Seems unlikely, but perhaps it has been down for two months?

For example, if you go to this url, 

> <https://ccdb.tau.ac.il/services/countsPartial/?genus=Solanum>

what you see is a page with "TAU websites are now under active maintenance and will be back shortly."

**Comment by Tbuchloh1** [comment]
The database seems to be up and running again, however the chrom_counts() function now throws a 404 error. I think the url must have changed with the most recent maintenance? For example, the link to the CCDB homepage on the package's github front page is incorrect and does not take you to the CCDB. Is this an easy fix?

**Comment by kbroman** [comment]
The database has moved to <https://taux.evolseq.net/CCDB_web>, but [the website still lists](https://taux.evolseq.net/CCDB_web/services/) the same URL for the API, <https://ccdb.tau.ac.il/services/>, but it seems like it has been changed to <https://taux.evolseq.net/CCDB_web/services>.

**Comment by kbroman** [comment]
We're back up and running, and a new, working version of chromer is on its way to CRAN. Thanks, @Tbuchloh1!
