### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by Tbuchloh1** [ropensci/chromer#40]
The database seems to be up and running again, however the chrom_counts() function now throws a 404 error. I think the url must have changed with the most recent maintenance. For example, the link to the CCDB homepage on the package's github page is incorrect and does not take you to the CCDB. Is this an easy fix?

**Comment by kbroman** [comment]
Should be an easy fix. Looks like the API has moved to <https://taux.evolseq.net/CCDB_web/services>.

**Comment by kbroman** [comment]
We're back up and running, and a new, working version of chromer is on its way to CRAN. Thanks, @Tbuchloh1!
